title: Comparative Judgement Research Consortium

plugins:
  - jekyll-scholar
  - jekyll-scholar-csl
  - jekyll-remote-theme

baseurl: '/Comparative-Judgement-Research-Consortium'

scholar:
  csl: ./_styles/apa_hyperlinks.csl
  locale: en

remote_theme: HiddenHarmsHub/jekyll-theme-zendesk-garden@main
repository: catsmith/Comparative-Judgement-Research-Consortium
search_enabled: true
auto_page_title: true
sidebar:
    - index
    - label: Meetings
      children:
        - 2024-january
        - 2024-september
        - 2025-january
        - 2025-april
        - 2026-january
    - label: Resources
      children:
        - articles
        - guidance
        - repo
        - software
    - reading_group
    - barriers
